name: Bug report
description: Create a bug report to help us address errors in the repository
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >
        Before requesting please search [existing issues](https://t.me/c/1937296927/3602/25534).

  - type: input
    attributes:
      label: "Video"
      description: >
        insert a link to a YouTube video where you demonstrate the problem and show how to reproduce it
      placeholder: "link to the video"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Dependencies version (pip freeze)"
      description: >
        This is the output of the command `pip freeze --all`. Note that the
        actual output might be different as compared to the placeholder text.
      placeholder: |
        appnope==0.1.3
        asttokens==2.0.8
        backcall==0.2.0
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe the behavior you expect. May include images or videos."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual behavior"
    validations:
      required: true
