name: "SENATOROV"
permissions:
  contents: write 
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 0 * * *" # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:
  pull_request:
    branches:
      - "**"
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install --user bandit
      - run: bandit $(git ls-files '*.py' '*.ipynb')  
