name: directory_writer
permissions:
  contents: write
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set script executable permission
        run: chmod +x scripts/build_directory_md.py
      - name: Write DIRECTORY.md
        run: |
          scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "SENATOROV updating DIRECTORY.md" || echo "No changes to commit"
          git push --force
    

